version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongo/movies:/docker-entrypoint-initdb.d/movies:rw
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:rw
    networks:
      - practica_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    depends_on:
      - mongo
    ports:
      - 9001:8080
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ['node', 'index.js']
    networks:
      - practica_network

  mongo-express:
    image: mongo-express:latest
    container_name: adminMongo_container
    depends_on:
      - mongo
    ports:
      - 9081:8081
    networks:
      - practica_network

networks:
  practica_network:
    driver: bridge
# Para iniciar: docker-compose up --build -d
