version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongo/movies:/docker-entrypoint-initdb.d/movies:ro
    networks:
      - practica_network

  backend:
    build: .
    container_name: backend_container
    depends_on:
      - mongo
    ports:
      - 8080:8080
    volumes:
      - ./src:/app
    working_dir: /app
    command: ['node', 'index.js']
    networks:
      - practica_network

networks:
  practica_network:
    driver: bridge
# Para iniciar: docker-compose up --build -d mongo
